server:
  port: 8081
  session:
    timeout: 2592000 # Session timeout in seconds.
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  thymeleaf:
    cache: false
#  redis:
#    host: master-ump-server
#    port: 6379
#    password: ump@2018 206.189.41.190
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  messages:
      basename: messages/messages
      cache-seconds: -1
      encoding: UTF-8
apiEndpointUrl: http://automaster.alliedsoft.hu:9092
